name: lista_de_tarefas
description: A new Flutter application.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^0.1.3
  path_provider: ^1.1.0


dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

 